config/routes.rb
Bandwagon::Application.routes.draw do
  devise_for :users
  get "static_pages/home"  
  get "static_pages/test"
  get "static_pages/eblast"
  get "waitlists/transition"
  get 'about', to: 'static_pages#about', as: :about

  get 'archive', to: 'categories#index', as: :archive

  match '/collectemails/unsubscribe/:unsubscribe_token' => 'collectemails#unsubscribe', as: 'unsubscribe', via: [:get, :post]

  root to: 'static_pages#home'

  resources :blurbs, only: [:create, :destroy, :update, :edit]
  resources :categories, only: [:create, :destroy, :update, :edit, :new, :show]
  resources :collectemails, only: [:create]
  resources :waitlists, only: [:create, :destroy]

  authenticate :user do
    mount Resque::Server, at: "/resque"
  end

end

app/models/blurb.rb
class Blurb < ActiveRecord::Base
	validates :content, presence: true

	validates :category_id, presence: true
	validates :name, presence: true

	belongs_to :category

	default_scope order('updated_at DESC')
end

app/controllers/blurbs_controller.rb
class BlurbsController < ApplicationController
	before_filter :authenticate_user!

	def create
		@blurb = Blurb.new(blurb_params)
		if @blurb.save
			flash[:success] = "Blurb created!"
			redirect_to :back
		else
			flash[:notice] = "Blurb not created!"
			redirect_to :back
		end
	end

	def destroy
		@category = Blurb.find(params[:id]).category
		Blurb.find(params[:id]).destroy
		flash[:success] = "Blurb destroyed!"
		redirect_to @category
	end

	def edit
		@blurb = Blurb.find(params[:id])
	end

	def update
		@blurb = Blurb.find(params[:id])
		if @blurb.update_attributes(blurb_params)
			flash[:success] = "Blurb updated!"
			redirect_to @blurb.category
		else
			flash[:notice] = "Blurb not updated!"
			render 'edit'
		end
	end

private
	def blurb_params
		params.require(:blurb).permit(:content, :category_id, :name)
	end
end

app/helpers/blurbs_helper.rb
module BlurbsHelper
end

app/views/blurbs/_blurb.html.erb
<li>
	<% if !blurb.name.nil? %>
	  <span class="content">
	  	<h3>
	  		<%= blurb.name.upcase %>
	  	</h3>
	  	<% if user_signed_in? %>
			<%= link_to 'Edit', edit_blurb_path(blurb) %>
			<%= link_to 'Delete', blurb, method: :delete, data: {confirm: "You sure?"} %>
		<% end %>
	  </span>
	  <div class="bandwagn-blurb"><%= raw(blurb.content) %></div>
	 <% end %>
</li>

app/views/blurbs/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@blurb) do |f| %>
    
      <%= f.label :name %>
      <%= f.text_field :name %>  
      
      <%= f.label :content %>
      <%= f.cktext_area :content %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>