config/routes.rb
Bandwagon::Application.routes.draw do
  devise_for :users
  get "static_pages/home"  
  get "static_pages/test"
  get "static_pages/eblast"
  get "waitlists/transition"
  get 'about', to: 'static_pages#about', as: :about

  get 'archive', to: 'categories#index', as: :archive

  match '/collectemails/unsubscribe/:unsubscribe_token' => 'collectemails#unsubscribe', as: 'unsubscribe', via: [:get, :post]

  root to: 'static_pages#home'

  resources :blurbs, only: [:create, :destroy, :update, :edit]
  resources :categories, only: [:create, :destroy, :update, :edit, :new, :show]
  resources :collectemails, only: [:create]
  resources :waitlists, only: [:create, :destroy]

  authenticate :user do
    mount Resque::Server, at: "/resque"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :title, presence: true
	validates_inclusion_of :show_to_users, :in => [true, false]
	
	has_many :blurbs, dependent: :destroy
	default_scope order('created_at DESC')

	def to_param
		title
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]

  def show
    @category_for_email = Category.where(show_to_users: true).first

    
  	@category = Category.find_by_title(params[:id])
  	@blurbs = @category.blurbs
  	@blurb = @category.blurbs.build

    @email = Collectemail.new
  end

  def new
  	@category = Category.new
  end

  def create
  	@category = Category.new(category_params)
  	if @category.save
  		flash[:success] = "Email created!"
  		redirect_to @category
  	else
  		flash[:notice] = "New email no created!"
      redirect_to :back
  	end
  end

  def edit
  	@category = Category.find_by_title(params[:id])
  end

  def update
  	@category = Category.find_by_title(params[:id])
  	if @category.update_attributes(category_params)
  		flash[:success] = "Email updated!"
  		redirect_to @category
  	else
  		flash[:notice] = "Email not updated!"
  		render 'edit'
  	end
  end

  def destroy
  	Category.find_by_title(params[:id]).destroy
  	flash[:success] = "Email destroyed!"
  	redirect_to Category.first
  end

  def index
    @categories_for_users = Category.where(show_to_users: true).limit(20)[5..19]
    @categories_for_mm = Category.all
  end

 private
 	def category_params
 		params.require(:category).permit(:title, :description, :show_to_users, :send_date)
 	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<div class="row">
<br>
<br>
<br>
<br>

	<div class="span4">
		<section>
			<%= form_for(@category) do |f| %>
				<%= f.text_field :title, placeholder: "Enter a title..." %>
				<br>
				<%= f.label :show_to_users, "Display in archive?" %>
				<%= f.check_box :show_to_users %>
				<br><br>
				<%= f.text_area :description, placeholder: "Enter a description or quote of the day..." %>
				<%= f.submit "Post", class: "btn btn-large btn_primary" %>
			<% end %>
		</section>
	</div>
</div>

app/views/categories/index.html.erb
<div class="fullbleedouter">
	<div class="fullbleedinner"></div>
	<img src="/assets/white-writing2.png">
</div>


<div class="wrapme">
	</br>

	<ul style="margin: 0 auto; text-align:center;">
		<%= link_to "<< Back to signup", root_path %>
		</br></br>
		<h1>Archive</h1>
		</br>
		<% if user_signed_in? %>
			<% @categories_for_mm.each do |c| %>
				<li style="list-style-type:none;">
					<% if c.send_date.present? %>
						<%= link_to "theBandwagn from " + c.send_date.strftime("%B %e").to_s, c %> |
					<% else %>
						<%= link_to "theBandwagn from " + c.created_at.strftime("%B %e").to_s, c %> |
					<% end %>
					<%= link_to "Edit", edit_category_path(c) %> |
					<%= link_to "Destroy", c, method: :delete, data: {confirm: "You sure?"} %> |
					<%= c.show_to_users %>
				</li>
			<% end %>
		<% else %>
			<% @categories_for_users.each do |c| %>
				<li style="list-style-type:none;">
					<% if c.send_date.present? %>
						<%= link_to "theBandwagn from " + c.send_date.strftime("%B %e").to_s, c %>
					<% else %>
						<%= link_to "theBandwagn from " + c.created_at.strftime("%B %e").to_s, c %>
					<% end %>
				</li>
			<% end %>
		<% end %>
	</ul>
</div>
</br>
</br>
</br>

app/views/categories/new.html.erb
<div class="row">
<br>
<br>
<br>
<br>

	<div class="span4">
		<section>
			<%= form_for(@category) do |f| %>
				<%= f.text_field :title, placeholder: "Enter a title..." %>
				</br>
				<%= f.label :show_to_users, "Display in archive?" %>
				
				<%= f.check_box :show_to_users %>
				</br></br>
				<%= f.text_area :description, placeholder: "Enter a description or quote of the day..." %>
				<%= f.submit "Post", class: "btn btn-large btn_primary" %>
			<% end %>
		</section>
	</div>
</div>

app/views/categories/show.html.erb
<div class="fullbleedouter">
	<div class="fullbleedinner"></div>
	<img src="/assets/white-writing2.png">
</div>


<div class="wrapme">

	<div style="margin: 0 auto;">

		<% if user_signed_in? %>
			<%= link_to 'Create a new email', new_category_path %><br>
			<% if @category == @category_for_email %>
				This is the email that will be sent.
			<% else %>
				This is NOT the email that will be sent.
			<% end %>
		<% end %>
		<br>
		<div class="mycat">
			<% if @blurbs.any? %>
				<h2 style="text-align:center;"><%= @category.title %></h2>

				<% if @category.send_date.present? %>
					<div style="text-align:center;"><%= @category.send_date.strftime("%B %e, %Y").to_s %></div>
				<% else %>
					<div style="text-align:center;"><%= @category.created_at.strftime("%B %e, %Y").to_s %></div>
				<% end %>

				<br>
				<div style="text-align:center;">
					<%= link_to "<< Signup", root_path %> | <%= link_to "<< Archive", archive_path %>
				</div>
				<h3>STAT OF THE DAY</h3>
				<p class="bandwagn-blurb"><%= raw(@category.description) %></p>
				<p>
					<% if user_signed_in? %>
						<%= form_for(@blurb) do |f| %>
							<%= f.text_field :name, placeholder: "Enter a headline..." %>
							<%= f.cktext_area :content, placeholder: "Compose new blurb..." %>
							<%= f.hidden_field :category_id, value: @category.id %>
							<%= f.submit "Post", class: "btn btn-large btn-primary" %>
						<% end %>
					<% end %>
				</p>
				<ol class="blurbs">
					<%= render @blurbs %>
				</ol>

			<% else %>
				<%= "Not much to mention right now.  This sport will probs become relevant in a few months." %>
			<% end %>
		</div>
	</div></br>
</div>