config/routes.rb
Bandwagon::Application.routes.draw do
  devise_for :users
  get "static_pages/home"  
  get "static_pages/test"
  get "static_pages/eblast"
  get "waitlists/transition"
  get 'about', to: 'static_pages#about', as: :about

  get 'archive', to: 'categories#index', as: :archive

  match '/collectemails/unsubscribe/:unsubscribe_token' => 'collectemails#unsubscribe', as: 'unsubscribe', via: [:get, :post]

  root to: 'static_pages#home'

  resources :blurbs, only: [:create, :destroy, :update, :edit]
  resources :categories, only: [:create, :destroy, :update, :edit, :new, :show]
  resources :collectemails, only: [:create]
  resources :waitlists, only: [:create, :destroy]

  authenticate :user do
    mount Resque::Server, at: "/resque"
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>Grizzlybearded Productions</p>
  </small>
  <nav>
  	<% if user_signed_in? %>
    <ul>
      <li>Subs: <%= Collectemail.where(send_email: true).count %></li>  
      <li>Unsubs: <%= Collectemail.where(send_email: false).count %></li>
    </ul>
    <% end %>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "theBandwagn", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li style="font-weight:bold; font-size:2em;"><%= link_to 'Home', root_path %></li>
          <li style="font-weight:bold; font-size:2em;"><%= link_to 'Archive', archive_path %></li>
          <li style="font-weight:bold; font-size:2em;"><%= link_to 'Waitlist ('+Waitlist.all.count.to_s+')', waitlists_transition_path %>
          </li>
          <li><%= link_to 'Test Email', static_pages_test_path, confirm: 'Are you sure?' %></li>
          <li><%= link_to 'E-Blast', static_pages_eblast_path, confirm: 'Are you sure?' %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>theBandwagn</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="google-site-verification" content="BB_59ZvursW6eKsfaXGG5J_Vt56A1HIc5UDVxuxY5CU" />
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-sacle=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="HandheldFriendly" content="true">
  
  <%= favicon_link_tag 'favicon.png' %>

  <%= render 'layouts/shim' %>
</head>
<body>
	<% if user_signed_in? %>
		<%= render 'layouts/header' %>
	<% end %>
	<div class="container">
		<% flash.each do |key, value| %>
        	<div class="alert alert-<%= key %>"><%= value %></div>
      	<% end %>
		<%= yield %>	
	</div>
	<% if user_signed_in? %>
		<%= render 'layouts/footer' %>
	<% end %>
	<div class="container">
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>